### ISSUE TITLE
too many initializers

### ISSUE THREAD

**Issue by bachittle** [PABannier/encodec.cpp#31]
get the following errors when compiling main and v0.1.0:
![image](https://github.com/PABannier/encodec.cpp/assets/39804642/a9283b88-65ea-4bff-b8e4-c50eed2f2ab7)

It is related to ggml.c compilation, I believe you are using a custom fork with changes to it, and that version is not working, but it was since October 2023 so I'm unsure what the reason is. 

Maybe it's because I'm using MSVC and Windows instead of Mac?

**Comment by PABannier** [comment]
Hi @bachittle ! Thanks for flagging this error. I just tried to compile the codebase, and it works fine on my Mac M1 Pro.
Indeed, I suspect that the problem is stemming from your OS. I do not currently have CIs for Windows + MSVC. 

Have you tried cloning [ggml](https://github.com/ggerganov/ggml) and compiling it?

**Comment by bachittle** [comment]
So the master branch of ggml compiles with MSVC just fine, I believe it is just the version in this submodule (since some changes have been made to it). Also confirming my theory, GCC and clang compile just fine, so it is definitely an MSVC issue.

**Comment by PABannier** [comment]
Alright! Thanks for checking. I'll add some CIs testing MSVC and Windows. Currently, we only have CIs for MacOS and Linux. Do you know what can cause these `too many initializers` errors?

**Comment by bachittle** [comment]
Here is a PR: https://github.com/PABannier/encodec.cpp/pull/32
It allows for compilation on Windows, but I have yet to test if it runs without errors. 

I also made a PR to your ggml fork to keep that in sync with this projects ggml submodule: https://github.com/PABannier/ggml/pull/1
