### ISSUE TITLE
Enable option to build .so files for Python binding with Ctypes

### ISSUE THREAD

**Issue by tranminhduc4796** [PABannier/encodec.cpp#47]
I am writing Python binding for bark.cpp and due to the specific `add_library(${ENCODEC_LIB} STATIC encodec.cpp encodec.h)`, I could not use a high-level CmakeLists.txt to build the .so file for encodec.cpp. We should add option to build share library:

`
option(BUILD_SHARED_LIBS "build shared libraries" OFF)
add_library(${ENCODEC_LIB} encodec.cpp encodec.h)
`
This should be applied on the bark.cpp as well

**Comment by tranminhduc4796** [comment]
I created a PR https://github.com/PABannier/encodec.cpp/pull/48 for this issue. Would you mind taking a look when you have a chance? It'll help us get the Python bindings for bark.cpp ready.

**Comment by PABannier** [comment]
Thank you very much @tranminhduc4796 . Just merged #48 . Does that fix the issue?

**Comment by tranminhduc4796** [comment]
Actually, I still need to wait for the success PR of bark.cpp syncing up with the latest encoded https://github.com/PABannier/bark.cpp/pull/199 to be able to apply this PR. But anyway, thank you for your great support. I will close this issue.

**Comment by PABannier** [comment]
Well-noted, I'll try to finish it this week-end.
